overrides:
  - files:
    - '**/test/**/*.js'
    - '**/test.js'
    env:
      mocha: true
      node: true
  - files:
    - '**/__tests__/*.js'
    env:
      node: true

env:
  shared-node-browser: true

plugins:
  - import

extends: freighter-repo

rules:
  flowtype/require-valid-file-annotation: off
  lines-around-comment: off
  no-duplicate-imports: off
  import/no-duplicates: error
