env:
  shared-node-browser: true
  commonjs: true
  mocha: true
  jest: true
  es6: true

plugins:
  - import

extends:
  - eslint:recommended
  - llama
  - prettier

globals:
  Generator: true
  Iterable: true

parser: babel-eslint
parserOptions:
  sourceType: module

rules:
  lines-around-comment: off
  no-duplicate-imports: off
  import/no-duplicates: error
