env:
  shared-node-browser: true
  commonjs: true
  mocha: true
  jest: true
  es6: true

plugins:
  - import
  - flowtype

extends:
  - eslint:recommended
  - plugin:flowtype/recommended
  - llama
  - prettier

parser: babel-eslint
parserOptions:
  sourceType: module

rules:
  lines-around-comment: off
  no-duplicate-imports: off
  import/no-duplicates: error
