env:
  shared-node-browser: true
  commonjs: true
  mocha: true
  jest: true
  es6: true

extends:
  - eslint:recommended
  - llama
  - prettier

parser: babel-eslint
plugins:
  - babel

parserOptions:
  sourceType: module
