---
language: node_js

node_js:
- 4
- 5
- 6

before_script:
- yarn lerna bootstrap

script:
  # Forces colors in test output.
  # Passes commands through lerna, then to npm, then to mocha.
- yarn lerna run test -- -- -- --colors
- yarn lerna run lint
